version: "3.8"

services:
  client:
    build: .
    command: npm run dev
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=4000
      - API_URL=http://localhost:4000/api/
